#!/bin/bash

echo "export TERM=xterm-256color" >> ~/.bashrc

set -euo pipefail

if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:wcl6-ml/MyDotfiles.git 
fi

exit 0


# install persoanl required packages that are not compatible with mise - wcl
sudo apt update && sudo apt install vim tree -y
