#!/bin/bash

set -euo pipefail

if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:wcl6-ml/MyDotfiles.git 
fi

exit 0


sudo apt update && sudo apt-get install tree -y
# install persoanl required packages that are not compatible with mise - wcl
